TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a7
TARGET_BOARD_PLATFORM := exynos4
TARGET_SOC := exynos4x12
TARGET_CPU_VARIANT := generic